package ch10.e04;

import java.util.Arrays;

public class E04 {
    //The code is generated by ChatGPT-3
    public static void run() {
        int n = 91; // Less than or equal to 91
        Matrix[] matrices = new Matrix[n];
        Arrays.parallelSetAll(matrices, i -> new Matrix(1, 1, 1, 0));
        Arrays.parallelPrefix(matrices, (a, b) -> a.multiply(b));
        long fib = matrices[n - 1].getData()[0][0];
        System.out.println("Fibonacci(" + n + ") = " + fib);
    }
}